version: "3"

services:
  app:
    depends_on:
      - selenium
    build: ./app
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true

  selenium:
    image: selenium/standalone-firefox-debug:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444
      - 5900:5900

